[package]
name = "earthstar"
version = "0.1.0"
edition = "2021"

[dependencies]
either = "1.10.0"
willow-data-model = { path = "../data-model" }
arbitrary = { version = "1.0.2", features = ["derive"]}
ufotofu = { path = "../../ufotofu" }